### ISSUE TITLE
运行  python3 main.py 出错

### ISSUE THREAD

**Issue by dearmin** [xiejiangzhao/Ding-Bot#1]
运行  python3 main.py
显示：
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from telegram import Bot
ModuleNotFoundError: No module named 'telegram'
```
ubuntu 18.04 64bit
 pip install -r requirements.txt
运行过了，无错。

**Comment by xiejiangzhao** [comment]
抱歉，使用pipreq生成requirement时引入了过时的包，代码已经重新push一遍，修改了相关的问题；
执行以下语句即可
```
pip uninstall python-telegram-bot telegram
pip install -r requirements.txt
```

**Comment by dearmin** [comment]
报错变成：
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from telegram import Bot
ModuleNotFoundError: No module named 'telegram'

```

**Comment by xiejiangzhao** [comment]
将pip 替换为pip3试一下

**Comment by dearmin** [comment]
嗯，谢谢，是python3的关系，安装pip3，就能正确运行了
```
2020-02-10 01:21:28,886 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
2020-02-10 01:22:28,886 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
2020-02-10 01:23:28,885 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
2020-02-10 01:24:28,886 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
2020-02-10 01:25:28,885 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
2020-02-10 01:26:28,886 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
2020-02-10 01:27:28,886 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
2020-02-10 01:28:28,886 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
2020-02-10 01:29:28,886 ERROR: An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/root/Ding-Bot/tmall_item.py", line 171, in record_status
    sku_id, area = self.bot_database.get_sku_area()[0]
IndexError: list index out of range
```
就是解析商品还有有错，上面是终端报错，
贴图是电报显示：

![无标题](https://user-images.githubusercontent.com/13921174/74106860-43f46a80-4ba5-11ea-886d-8dc90d597df2.png)

**Comment by xiejiangzhao** [comment]
第一次见到这种分享链接，可能是平台不同问题，已经更新到代码里面去了，覆盖文件即可使用，感谢提问！

**Comment by dearmin** [comment]
嗯嗯，这次没有出错了。

谢谢！
